server:
  host: 0.0.0.0
  gateway: 0.0.0.0
  port: 8888
  request_timeout: 30
 
db:
  host: 127.0.0.1
  port: 3306
  user: backend
  password: 123456
  dbname: iptv
 
agentgateway:
  host: "127.0.0.1"
  port: 8000
  storage: "./asset"

warmup:
  concurrency: 10
  migration_interval: 60

nra:
  concurrency: 10

redis:
  host: "127.0.0.1"
  port: 6379
  password: ""
  key: "agent_warmup"
  dial_timeout: 10 #second
  read_timeout: 30 #second
  write_timeout: 60 #second
  pool_size: 10 #second
  pool_timeout: 30 #second

mq:
  host: "127.0.0.1"
  port: 9092
  warmup_topic: "warmup"
  nra_topic: "nra"
  nra_reply_topc: "nra-reply"
  operation_topic: "operation"

rpc:
  agent:
    host: "0.0.0.0"
    gateway: "localhost"
    port: 50006
  agentctl:
    host: "0.0.0.0"
    gateway: "localhost"
    port: 50020


agentd:
  master:
    host: "127.0.0.1"
    port: 45656
    WorkingDir:
    IsDebugEnable:
    PathFileLog:
    RetryConnectTime:
  worker:
    MaxLifeTime: 600
    MinThread: 1
    MaxThread: 20


