// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/ctl/master/": {
            "post": {
                "description": "Control agentd",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Control agentd",
                "parameters": [
                    {
                        "description": "Input params",
                        "name": "model.AgentCtlRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.AgentCtlRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "True",
                        "schema": {
                            "$ref": "#/definitions/model.AgentCtlResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid param!!",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.AgentCtlDataResponse": {
            "type": "object",
            "properties": {
                "control_id": {
                    "description": "Control ID from frontend",
                    "type": "integer"
                },
                "control_type": {
                    "description": "Control type, define from backend\n\t\t\t\t// start agent\n\t\t\t\tStartAgentd = 10000\n\t\t\t\t// stop agent\n\t\t\t\tStopAgentd = 10001\n\t\t\t\t// Connect agent\n\t\t\t\tConnectAgentd = 10030\n\t\t\t\t// Disconnect agent\n\t\t\t\tDisconnectAgentd = 10031\n\t\t\t\t// Start Worker\n\t\t\t\tStartWorker = 20000\n\t\t\t\t// Stop worker\n\t\t\t\tStopWorker = 20001\n\t\t\t\t//Update Worker\n\t\t\t\tUpdateWorker = 20010\n\t\t\t\tSignal = 70001\n\t\t\t\tVideo = 70002\n\t\t\t\tAudio = 70003\n\t\t\t\tBlackScreen = 70004",
                    "type": "integer"
                }
            }
        },
        "model.AgentCtlRequest": {
            "type": "object",
            "properties": {
                "agent_ip": {
                    "description": "Agent control ip",
                    "type": "string"
                },
                "control_id": {
                    "description": "Control ID from frontend",
                    "type": "integer"
                },
                "control_type": {
                    "description": "Control type, define from backend\n\t\t\t// start agent\n\t\t\tStartAgentd = 10000\n\t\t\t// stop agent\n\t\t\tStopAgentd = 10001\n\t\t\t// Connect agent\n\t\t\tConnectAgentd = 10030\n\t\t\t// Disconnect agent\n\t\t\tDisconnectAgentd = 10031\n\t\t\t// Start Worker\n\t\t\tStartWorker = 20000\n\t\t\t// Stop worker\n\t\t\tStopWorker = 20001\n\t\t\t//Update Worker\n\t\t\tUpdateWorker = 20010\n\t\t\tSignal = 70001\n\t\t\tVideo = 70002\n\t\t\tAudio = 70003\n\t\t\tBlackScreen = 70004",
                    "type": "integer"
                },
                "tunnel_data": {
                    "description": "Data transmit through frontend --\u003e backend --\u003e agent --\u003e backend --\u003e frontend",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                }
            }
        },
        "model.AgentCtlResponse": {
            "type": "object",
            "properties": {
                "return_code": {
                    "description": "Return code\n\t\t1 - Success\n\t\t0 - Fail",
                    "type": "string"
                },
                "return_data": {
                    "description": "Data",
                    "$ref": "#/definitions/model.AgentCtlDataResponse"
                },
                "return_message": {
                    "description": "Message success or fail",
                    "type": "string"
                },
                "tunnel_data": {
                    "description": "Data transmit through frontend --\u003e backend --\u003e agent --\u003e backend --\u003e frontend",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "",
	Host:        "",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "",
	Description: "",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
